- name: Generate private keys
  shell: openssl genrsa 4096 > {{ letsencrypt_keys_dir }}/{{ item.key }}.key
  args:
    creates: "{{ letsencrypt_keys_dir }}/{{ item.key }}.key"
  when: site_uses_letsencrypt
  with_dict: "{{ wordpress_sites }}"

- name: Ensure correct permissions on private keys
  file:
    path: "{{ letsencrypt_keys_dir }}/{{ item.key }}.key"
    mode: 0600
  when: site_uses_letsencrypt
  with_dict: "{{ wordpress_sites }}"

- name: Generate CSRs
  shell: "openssl req -new -sha256 -key '{{ letsencrypt_keys_dir }}/{{ item.key }}.key' -subj '/' -reqexts SAN -config <(cat /etc/ssl/openssl.cnf <(printf '[SAN]\nsubjectAltName=DNS:{{ site_hosts | join(',DNS:') }}')) > {{ acme_tiny_data_directory }}/csrs/{{ item.key }}-{{ site_hosts_hash }}.csr"
  args:
    executable: /bin/bash
    creates: "{{ acme_tiny_data_directory }}/csrs/{{ item.key }}-{{ site_hosts_hash }}.csr"
  when: site_uses_letsencrypt
  with_dict: "{{ wordpress_sites }}"

- name: Generate the initial certificate
  command: ./renew-certs.py
  args:
    chdir: "{{ acme_tiny_data_directory }}"
  register: generate_initial_cert
  changed_when: generate_initial_cert.stdout is defined and 'Created' in generate_initial_cert.stdout
  notify: reload nginx

- name: Disable Nginx site
  file:
    path: "{{ nginx_path }}/sites-enabled/letsencrypt-{{ item.key }}-{{ site_hosts_hash }}.conf"
    state: absent
  with_dict: "{{ wordpress_sites }}"
  notify: reload nginx
